# Dependencies
markdown:         kramdown
kramdown:
  input:          GFM

highlighter:      rouge

# Setup
title:            Sandstone HPC
baseurl:          /

author:
  name:           'Zebula Sampedro'
  url:            https://sandstonehpc.github.io/

collections:
  docs:
    output:       true
    permalink:    /docs/:path/
